### ISSUE TITLE
Installing Edda for Amazon Linux Fails

### ISSUE THREAD

**Issue by efreedom79** [Answers4AWS/netflixoss-ansible#14]
The first error occurs when Ansible tries to start up mongod. Basically it fails.  Looking into the logs we see the error is:  "/usr/bin/mongod: symbol lookup error: /usr/bin/mongod: undefined symbol: _ZN7pcrecpp2RE4InitEPKcPKNS_10RE_OptionsE."

So looking that up said to use 10gen for the yum install. I modifed the tasks to include
- name: Install Selected Yum Repository for MongoDB
  copy: src=../files/mongodb.repo dest=/etc/yum.repos.d/mongodb.repo
  when: ansible_distribution == 'Amazon'
  tags: mongodb
- name: Install MongoDB (yum version)
  yum: pkg={{ item }} state=latest
  with_items:
  - mongo-10gen
  - mongo-10gen-server
    when: ansible_distribution == 'Amazon'
    tags: mongodb

and the repository set to: 

[mongodb]
name=MongoDB Repository
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
gpgcheck=0
enabled=1

Yay! After removing the old mongodb package, it ran a bit further. and stopped on this Task:

TASK: [edda | Download snapshot build of Edda from Cloudbees] *****************
failed: [ec2-54-242-11-34.compute-1.amazonaws.com] => {"dest": "/usr/local/tomcat/webapps/edda.war", "failed": true, "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://netflixoss.ci.cloudbees.com/job/edda-master/lastSuccessfulBuild/artifact/build/libs/edda-2.1-SNAPSHOT.war"}
msg: Request failed

I fixed the vars to show: https://netflixoss.ci.cloudbees.com/job/edda-master/lastSuccessfulBuild/artifact/build/libs/edda-2.2.0-SNAPSHOT.war as the new war file.

And that seems to allow it to go through to completion now.

**Comment by pas256** [comment]
Thanks Bob. Can you please make this a PR and I can merge it in?

**Comment by pas256** [comment]
Closing in favor of a PR
