### ISSUE TITLE
ami-29910c13 not available for public?

### ISSUE THREAD

**Issue by ajuico** [Answers4AWS/netflixoss-ansible#18]
Hi, this is an error i'm getting, when looking to launch the ami from: https://github.com/Answers4AWS/netflixoss-ansible/wiki/AMIs-for-NetflixOSS#simian-army-24

We cannot proceed with your requested configuration. You cannot use this AMI (ami-29910c13).
This AMI has been deregistered, or you do not have permission to use it. Try again with another AMI for which you have permissions, or request permission to use this AMI from its owner

Also fails using the cloudformation script

**Comment by pas256** [comment]
You will need to build your own AMIs for this now as Answers for AWS does not host the AMIs anymore.
